sudo: false
language: ruby
cache: bundler
before_install:
 - npm install -g geojsonhint
branches:
  only:
    - master
rvm:
  - 2.2.2
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --empty-alt-ignore --url-ignore "#"
  - result=$(geojsonhint --json < _data/chapters.json); echo "$result"; ! grep -qF '"error":' <<< "$result"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer 
